WifiControl/CMakeLists.txt, WifiControl/Network.cpp, WifiControl/Network.h, WifiControl/WifiControl.cpp, WifiControl/WifiControl.h, WifiControl/WifiHAL.cpp, WifiControl/WifiHAL.h
=> [WiFiControl] Adding RDK HAL WiFi support

CMakeLists.txt, Power/.gitignore, Power/CMakeLists.txt, Power/Module.cpp, Power/Module.h, Power/Power.config, Power/Power.cpp, Power/Power.h, Power/PowerImplementation/Broadcom/PowerImplementation.cpp, Power/PowerImplementation/Stub/PowerImplementation.cpp
Tested using Power/Stub implementation on RPI3
=> Power Plugin integration

Compositor/Compositor.config
Please also check Buildroot pull request, they belong together.
Pierre is aware what this is about.
=> [Compositor] Add external nxserver option

Compositor/Compositor.cpp, Compositor/lib/RPI/Client/Implementation.cpp, Compositor/lib/RPI/Compositor/RPI.cpp
Debug build assert in PutBelow function corrected
[RPI] Clients putting to layer -1 while requesting for PutBelow to make the layer invisible
=> [Compositor]

RemoteControl/CMakeLists.txt, RemoteControl/RemoteControl.cpp, RemoteControl/RemoteControl.h, RemoteControl/RemoteControl_JsonRpcImpl.cpp
Please take a look on current implementation based on our yesterday dicussion.
@Sebastian I combined your output with implementation.
=> [REMOTE CONTROL] Add JSONRPC API

WebKitBrowser/CMakeLists.txt, WebKitBrowser/WebKitBrowser.cpp, WebKitBrowser/WebKitBrowser.h, WebKitBrowser/WebKitBrowser_JsonRpcImpl.cpp
JSON-RPC endpoints and notifications for the WebKitBrowser plugin
=> [WebKitBrowser] Add JSON-RPC endpoints

Compositor/lib/Wayland/Client/CMakeLists.txt, Compositor/lib/Wayland/Compositor/CMakeLists.txt
Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>
=> [Compositor] EGL CFlags added

WifiControl/Controller.cpp, WifiControl/Controller.h
- Scanning not ending
- Status not updating properly
- Not being able to delete first config entry
- Invalid data being stored in a config
=> [WPE-276][Wificontrol] Fixes for various issues.

DIALServer/DIALServer.cpp, DIALServer/DIALServer.h, DIALServer/Netflix.cpp, DIALServer/YouTube.cpp
Code reformatted using WPEFramework/Source/.clang-format
=> [DIALServer] Apply code formatting

Spark/CMakeLists.txt
Spark Plugin Implementation adding ESSOS Support as well
Signed-off-by: pavannandyala <pavan.nandyala@lnttechservices.com>
=> Adding Platform ESSOS Platform support as well to

Compositor/CMakeLists.txt, Compositor/Compositor.cpp, Compositor/Compositor.h, Compositor/CompositorJsonRpc.cpp, Compositor/CompositorPlugin.json, Compositor/CompositorPlugin.md, Compositor/lib/RPI/RPI.cpp
Added JSON-RPC API to Compositor (based on old REST API)
Also, fixed a bug where ZOrder returned empty strings at the beginning
=> [Compositor] Added JSON-RPC api to Compositor

DHCPServer/DHCPServerImplementation.cpp, DHCPServer/DHCPServerImplementation.h, DHCPServer/DHCPServerJsonRpc.cpp
Attempts to fix lease time handling.
=> [DHCPServer] Fix lease time handling

OpenCDMi/FrameworkRPC.cpp
=> [OpenCDMi] Add metadata retrieving

Power/PowerImplementation/Broadcom/PowerImplementation.cpp
The Worker thread in the Power plugin to process requests from
SetState() is running through a while loop continuously without blocking
itself waiting for any event. This is a busy wait loop causing high CPU
usage.
Add a new Event object to make the worker thread wait for events
signalled by SetState() to avoid the busy wait loop.
All of the changes are required for correct operation of the Power plugin under the use cases required by NOS.
=> Power: Fixes from NOS testing

RemoteControl/GreenPeak.cpp, RemoteControl/RemoteControl.cpp, RemoteControl/RemoteControl.h
This Commit add the implementation of a new interface IRemoteControl
to the RemoteControl plugin.
The new interface is meant to be used to register with the plugin for
any events from any of the KeyProducers defined in RemoteControl plugin
like GreenPeak("RF4CE"), IRRemote..etc.
Also, add the changes to get the Pairing related events from GreenPeak
RF4CE implementation to registered clients.
Events are received by IKeyHandler from KeyProducers, just as we are
doing for Keys, And this event is passed to IRemoteControl interface who
will finally pass the event to all the registered clients.
Signed-off-by: harikrishnan.p <harikris2012@gmail.com>
Tested with NOS box.
Created after applying review comments from https://github.com/WebPlatformForEmbedded/ThunderNanoServices/pull/207
Main changes …
=> Update: RemoteControl: Add changes to support sending events

NetworkControl/NetworkControl.cpp
Logging of error was in the successful path
=> [WPE-416][NetworkControll] Fix Network reporting persistant storage error

Power/PowerImplementation/Broadcom/PowerImplementation.cpp
In the original implementation of the Power plugin, it was observed that
not all power state changes are notified to the client registered.
Client are only informed when the device comes out of standby. Ideally
all the clients needs to be informed about all the state changes.
=> Power: Notify about all power state events to the registered client

Compositor/lib/Wayland/Westeros.cpp
- mouse move and mouse click events handled
Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>
=> compositor: mouse event handling

Monitor/Monitor.h
And ofc start as soon as any observee gets activated.
This spares scheduling some uneeded probes.
=> [WPE-260][Monitor] Stop probing if there's no active observee.

VolumeControl/Nexus/VolumeControlPlatform.cpp
Nexus dBs scale is -90 dB to 0 dB. Doing it linearly 50% means -45 dB
but gain of -45 dB means nothing can really be heard (-6dB gain is 50%).
This is why logarithmic scale needs to be used for dBs.
=> [WPE-517][VOLUMECONTROL] Use logarithmic scale dor dBs.

NetworkControl/DHCPClientImplementation.cpp, NetworkControl/DHCPClientImplementation.h, NetworkControl/NetworkControl.cpp, NetworkControl/NetworkControl.h
Also restricted NetworkControll to only have 1 IP at the time when it is assigned by DHCP server (mimics standard dhcp settings eg. on Ubuntu)
=> [NetworkControl] Fixed problems gateway not beeing updated on IP change

Cobalt/CobaltImplementation.cpp, DIALServer/DIALServer.cpp, DIALServer/DIALServer.h, DIALServer/YouTube.cpp
!!! important !!!
Needs at lest cobalt 2b05944b27596a50c2d94b02b358fb289980a990 to work
Implemented a possibility to change Cobalt URL during runtime. This allowed for DIAL to kick in when Cobalt is already running.
=> [DIAL][Cobalt][WPE-556] Enabled DIAL to attatch to Cobalt during runtime

WebPA/WebPAImplementation.cpp, WifiControl/WifiControl.h
Make plugins work with process launch changes introduced in RunC
integration
=> [Process] Launch parameters are now ordered
