WebPlatformForEmbedded/ThunderNanoServices

Power/Power.cpp, Power/Power.h, Power/PowerImplementation/Broadcom/PowerImplementation.cpp, Power/PowerImplementation/Stub/PowerImplementation.cpp
Putting clients in suspend mode is linked with Standby Query, but there was no resume call for clients when we awake the system from standby. "Awaking" is handled by platform at the first place, it changes nexus layer from standby to on state but there is no notification mech. to inform power plugin for resume. So we may need to notify Power plugin based on INotification. 
I also updated WpeFramework to introduce IPower::INotification https://github.com/WebPlatformForEmbedded/WPEFramework/tree/odeveci/power_resumed
If this PR is Ok, I will also merge that branch. 
Thanks
Ozgur
=> Introduce INotification to Resume clients

cmake/FindNexus.cmake
For Yocto refsw headers are installed in /usr/include/refsw and /usr/include/nxclient. However the current cmake expects (a Buildroot generate install) all headers to be in /usr/include/refsw.
This will result into the following error when building in RDKV/Yocto:
NexusServer.cpp:418:106: error: 'nxserverlib_init_extended' was not declared in this scope
|                      _instance = nxserverlib_init_extended(&_serverSettings, config.Authentication.Value());
Updated the cmake to look for both refsw and nxclient subdirs and set the LIBNEXUS_INCLUDE_DIRS accordingly.
Signed-off-by: wouterlucas <wouter@wouterlucas.com>
=> [Compositor] Support for splitted refsw and nxclient include directories

Streamer/Streamer.config
Some fixes and improvements around the automatic generation of the JSON config for the Streamer Plugin.
Commit 1 fixes a cmake syntax error when PLUGIN_STREAMER_STANDARD variable is not set.  
Commit 2 is for adding QAM related configs only when the selected implementation is indeed set to QAM.
=> [STREAMER] Some fixes around JSON config generation

WifiControl/Controller.h
This commit will fix bug in wificontrol plugin config put operation
The hang was cause due improper use of synchronization lock mechanism
in the code.
GetKey API internally tries to acquire the lock which is already acquired
by put method which results in hang. Put method and GetKey are in two
different thread.
Test Steps:
Put a configuration:
curl -d '{"ssid":"SSID", "psk":"***", "key":"WPA"}' -v -H "Content-Type: application/json" -v -X PUT http://ip:8082/Service/WifiControl/Config
=> WifiControl Plugin : PUT config operation hangs

WifiControl/Controller.h
This commit will fix bug in wificontrol plugin configuration
post and delete operation. The hang was caused due to
the improper use of synchronization lock mechanism in the code.
GetKey API internally tries to acquire the lock which is already
acquired by post|delete methods called, which results in hang.
post|delete methods.
Test Steps:
Add a configuration :
curl -d '{"ssid":"SSID", "psk":"**", "key":"WPA"}' -v -H "Content-Type:
application/json" -v -X PUT http://ip:8082/Service/WifiControl/Config
Update a configuration:
curl -d '{"ssid":"SSID", "psk":"**", "key":"WPA"}' -v -H "Content-Type:
application/json" -v -X POST http://ip:8082/Service/WifiControl/Config
Delete a configuration:
curl -X DELETE -v http://127.0.0.1:8082/Service/WifiControl/Config/SSID
=> Config POST and DELETE operation hangs

CMakeLists.txt, TestController/CMakeLists.txt, TestController/Core/TestAdministrator.cpp, TestController/Core/TestAdministrator.h, TestController/Core/TestBase.h, TestController/Core/TestCategoryBase.h, TestController/Core/TestMetadata.h, TestController/Core/Trace.h, TestController/Examples/Test1.cpp, TestController/Examples/Test2.cpp, TestController/Examples/Test3.cpp, TestController/Examples/Test4.cpp, TestController/Examples/TestCategory1.h, TestController/Examples/TestCategory2.h, TestController/Module.cpp, TestController/Module.h, TestController/TestController.config, TestController/TestController.cpp, TestController/TestController.h, TestController/TestControllerImp.cpp
TestController is a plugin, that allows to execute standalone tests.
Following REST API is exposed:
// GET /Service/<CALLSIGN>/TestCategories
// GET /Service/<CALLSIGN>/<TEST_CATEGORY>/Tests
// GET /Service/<CALLSIGN>/<TEST_CATEGORY>/<TEST_NAME>/Description
// POST/PUT /Service/<CALLSIGN>/TestCategories/Run
// POST/PUT /Service/<CALLSIGN>/<TEST_CATEGORY>/Run
// POST/PUT /Service/<CALLSIGN>/<TEST_CATEGORY>/<TEST_NAME>
=> [TestController] Add TestController plugin

CMakeLists.txt, TestUtility/CMakeLists.txt, TestUtility/CommandCore/TestCommandBase.h, TestUtility/CommandCore/TestCommandController.cpp, TestUtility/CommandCore/TestCommandController.h, TestUtility/CommandCore/TestCommandMetadata.h, TestUtility/CommandCore/TraceCategories.h, TestUtility/Commands/Crash.cpp, TestUtility/Commands/CrashCore.h, TestUtility/Commands/CrashNTimes.cpp, TestUtility/Commands/Free.cpp, TestUtility/Commands/Malloc.cpp, TestUtility/Commands/MemoryAllocation.h, TestUtility/Commands/Statm.cpp, TestUtility/Module.cpp, TestUtility/Module.h, TestUtility/TestUtility.config, TestUtility/TestUtility.cpp, TestUtility/TestUtility.h, TestUtility/TestUtilityImp.cpp
TestUtility is a plugin, that allows to execute commands, to simulate
specific test conditions. This plugin can:
* Allocate a specific amount of memory
* Free previously allocated memory
* Retrieve information about currently allocated memory
* Crash plugin
* Crash plugin N times in a row
This plugin is meant to be easily extensible.
=> [TestUtility] Add TestUtility plugin

tests/JSONRPCClient/JSONRPCClient.cpp
Fixes:
WPEFrameworkPlugins/tests/JSONRPCClient/JSONRPCClient.cpp:208:24: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
printf("received time: %llu - %d\n", response.Time.Value(), response.State.Value());
^~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~
=> Correct printf() arguments

WebKitBrowser/CMakeLists.txt, WebKitBrowser/WebKitImplementation.cpp, cmake/FindWPEBackend.cmake, cmake/FindWPEWebKit.cmake
Fixes needed in order to be able to compile with wpe-2.22 (without GLIB API yet).
The next (separate step) would be to add GLIP API on top of that.
=> 2.22 compilation fixes rebased on top of plugins' HEAD

WifiControl/Controller.h
On success the error code returned by Connect()/Disconnect() were
never set and the default value for them was set to UNKNOWN_KEY
meaning operation were always reporting failure.
=> [wificontrol] Update connect/disconnect operation status.

TimeSync/CMakeLists.txt, TimeSync/TimeSync.cpp, TimeSync/TimeSync.h, TimeSync/TimeSyncJsonRpc.cpp
- Modify the JSON-RPC implementation of TimeSync plugin to use the autogenerated files
- Add new "set" method to JSON-RPC and RESTful  interfaces to allowing setting of time from an external source
- Fix not-working RESTful "sync" call
=> [TimeSync] Allow setting the time from an external source

OpenCDMi/FrameworkRPC.cpp
Helps to fix errors on OCDM-Playready like;
error: ISO C++ forbids converting a string constant to ‘char*’
m_piCallback->OnKeyMessage((const uint8_t *) "", 0, "");
=> Constify OnKeyMessage() f_pszUrl parameter

OpenCDMi/CMakeLists.txt
Fixes the following error:
CMake Error at OpenCDMi/CMakeLists.txt:34 (target_link_libraries):
The keyword signature for target_link_libraries has already been used with
the target "WPEFrameworkOCDM".  All uses of target_link_libraries with a
target must be either all-keyword or all-plain.
The uses of the keyword signature are here:
* OpenCDMi/CMakeLists.txt:24 (target_link_libraries)
=> Fix cmake error

WifiControl/Controller.cpp, WifiControl/Controller.h
Everytime a request is to be submitted it's checked it's not in progress
by doing Set() on it. If Set() doesn't succeed it means a request is in
progress so there's no point in scheduling a new one. Submit() is even
asserting on that. However Set() success or failure was dependent on internal
request's message being empty or not. The problem was SendData() is clearing
that meassage yet the fact the message was sent doesn't mean it's done
processing. Receiving the response is such indicator. This is why it's now
assured that until response/cancellation request's Set() will fail preventint
its re-submition.
=> [WPE-295][wificontrol] Asure Submit() assert won't trigger.

OpenCDMi/CENCParser.h
Some content on Youtube (free with ads) fail to play. Example:
https://www.youtube.com/tv#/watch/video/control?v=jAsgMpwX5uk&resume
They have both Widevine and Playready keyIDs inside the PSSH box and since Playready DRM does not return the keyID when calling keyStatusUpdate(), only the first keyID found in the PSSH was being updated, in this case it is the wrong (Widevine) keyID.
This fix selects the first "Playready" keyID if no keyIDs are provided.
=> [OCDMi] update first Playready keyID when no keyID is provided from DRM

NetworkControl/DHCPClientImplementation.cpp, NetworkControl/DHCPClientImplementation.h, NetworkControl/NetworkControl.cpp, NetworkControl/NetworkControl.h
1. Fixed DHCP client sending ACK instead of REQUEST
2. Added IP retention - it is no longer changing on every reboot
=> DHCP Client now remembers previous IP

OpenCDMi/CENCParser.h
We have seen some content (Blacklist, Episode 15 on Amazon Prime) which has a PSSH box that was much bigger than the XML string. It was not being parsed properly
=> fix PSSH Playready XML parser

Compositor/lib/Wayland/NexusServer
@pwielders, wayland build for nexus is failing since the NexusServer link is not available in the expected path. Found that the link to NexusServer was removed @Commit: https://github.com/WebPlatformForEmbedded/ThunderNanoServices/commit/c0519fafc9b6177e6391f4381c62be7604c62f0d#diff-ae058ed81423bf369a3a1e5dd6ebb0d2L1. So I am note sure, can I restore it again.
=> Compositor: link to NexusServer restored

Compositor/lib/Wayland/Wayland.h
EGL headers use WL_EGL_PLATFORM define to define some generatic typedefs
based on X11/wayland/eglfs being the protocols, if we do not include
wayland-egl.h first then WL_EGL_PLATFORM does not get defined and it
defaults to X11 or eglfs depending upon distro features, since westeros
is a wayland compositor we should be defining WL_EGL_PLATFORM first and
then including EGL headers
Fixes errors like
Source/compositorclient/Wayland/Implementation.h:119:65: error: invalid static_cast from type 'wl_egl_window* const' to type 'EGLNativeWindowType' {aka 'long uns igned int'}
ource/compositorclient/Wayland/Implementation.h:565:63: error: invalid static_cast from type 'wl_display* const' to type 'EGLNativeDisplayType' {aka '_XDisplay*'}
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> compositorclient/westeros: Include wayland-egl.h before EGL headers

Compositor/lib/Nexus/CMakeLists.txt, Compositor/lib/Nexus/NexusServer/CMakeLists.txt
This fixes an error of a header file not found:
Compositor/lib/Nexus/NexusServer/NexusServer.h:6:25: fatal error: nxserverlib.h: No such file or directory
#include <nxserverlib.h>
Fixed by adding /usr/include/nxclient path as part of the include, as found per FindNXSERVER.cmake.
Ran into the above error on Yocto, can the cmake gods check this for me please? @bramoosterhuis
=> [compositor] Add nxserver include dirs to target.

WifiControl/WifiControl.h
Via implicit conversions with String(bool quoted) involved.
The mentioned Ctor will be made explicit as a separate change.
=> [WifiControl] BSSID is uint64_t and it's written to a JSON string.

OpenCDMi/OCDMJsonRpc.cpp
Fixed problem with empty keysystems returned in jsonrpc request to ocdm plugin.
Jira ticket WPE-320
=> [OpenCDMi] Fix empty keysystems in jsonrpc

Spark/Spark.config
This fixes an error when trying to compile Spark without Compositor. Without Compositor the value ${PLUGIN_COMPOSITOR_IMPLEMENTATION} is not present.
=> Spark: Only check STREQUAL if value exists

NetworkControl/DHCPClientImplementation.cpp, NetworkControl/DHCPClientImplementation.h, NetworkControl/NetworkControl.config, NetworkControl/NetworkControl.cpp, NetworkControl/NetworkControl.h
[WPE-357]
The socket is now properly closed when either DHCP successfully assing IP or a maximum number of retries were exceeded.
[WPE-356]
DHCPImplementation is now not aware of permanent storage. Its sole responsibility is to implement DHCP requests and process responses.  Moreover, now the only DHCPRequest is sent if IP was saved, which is correct behaviour in such a case. Full DHCPDisover is sent only if DHCPRequest fails.  Also, multiple interfaces are supported now.
[DHCPClient] - Full implementation
Previously IP was assigned only after receiving information, that this IP is available. Result of the request was ignored. Now IP is assigned only after it is successfully given by DHCP server. If the server refuses to assign IP, other offers are tried or another DHCPDiscover is issued …
=> [WPE-357][WPE-356][DHCPClient] Full implementation of minimal dhcp protocol

DHCPServer/DHCPServer.cpp, DHCPServer/DHCPServer.h, DHCPServer/DHCPServerImplementation.cpp, DHCPServer/DHCPServerImplementation.h
Leased IP are now stored over reboots, so devices should get the same ip.
It's easiest to test via creating access point on wifi interface but to do this at least somewhat reliable https://github.com/WebPlatformForEmbedded/ThunderNanoServices/pull/171 needs to be merged first
=> [WPE-220][DHCPServer] Saving ip leases to permanent storage

OpenCDMi/CENCParser.h
All CDMis now all have to send proper key ids (which they do).
=> [OCDM] Remove dead path and make sure it stays dead via assert.

OpenCDMi/FrameworkRPC.cpp
https://github.com/WebPlatformForEmbedded/Thunder/pull/227's complement
=> [OCDM] Always use DestroyMediaKeySession().

NetworkControl/NetworkControl.cpp, NetworkControl/NetworkControl.h
SaveLeases() function was mistakenly using Open() instead of Create() - that caused the lease file not to be truncated before saving. 
This could lead to a corrupted file if a new version of the file was shorter than the previous one.
Also changed "leaseFile" to "_leaseFile" to better follow convention.
Caught by @sebaszm
=> [NetworkControll ] Fixed using Open() instead of Create() while saving leases

Compositor/lib/Wayland/Wayland.h, Compositor/lib/Wayland/Westeros.cpp
In Thunder repository, since [this commit](https://github.com/WebPlatformForEmbedded/Thunder/commit/d19a474e2c1ee53fafb91b712cad3be64f24ff46#diff-faeeb027e7825401aa0b3ee6e837de38), the virtualinput API has changed. This causes build errors in ThunderNanoServices. The current patch solves the build issues. 
Note that I do not have a Westeros environment easily available. Can someone volunteer to test on a Westeros environment?
=> Compositor: Adjust to new virtualinput API

Compositor/Compositor.config, Compositor/lib/Nexus/NexusServer/NexusServer.cpp, Compositor/lib/Nexus/NexusServer/NexusServer.h
A few Compositor plugin fixes drafted after NOS testing with the latest framework.
Commit 1 (25e958b704d2) is for unregistering from the Nexus Standby Acknowledgment process. 
For backwards compatibility, by default Nexus has  Standby Acknowledgment enabled for every `NxClient_Join()`.
However, the Compositor is not implementing the Standby Acknowledgment and, as such, it should unregister itself from it, otherwise, when going to standby, Nexus will wait 10 seconds (the default timeout) from this client to acknowledge the standby.  
Any client that does `NxClient_Join()` but doesn't implement StandbyAcknowledgment must unregister itself from the Standby Acknowledgment process. 
Commit 2 (060f0a25e2b6) is to allow configuring the NxServer Audio Loudness Mode via the Compositor's JSON …
=> Compositor: Fixes from NOS testing

Streamer/Streamer.cpp, Streamer/Streamer.h, Streamer/StreamerImplementation.cpp, Streamer/StreamerImplementation.h
A few Streamer plugin fixes drafted after NOS testing with the latest framework.
Commit 1 (f2d1a9cbf646) fixes missing enum conversion tables.  
Commit 2 (c21973d31c03) fixes implementation for the ExternalAccess class to be according the the latest Thunder requirements.  
Commit 3 (c312b7e0e4ac) adds a missing registration to `RPC::IRemoteConnection::INotification`.
All of the fixes are required for correct operation of the Streamer plugin under the use cases required by NOS.
=> Streamer: Fixes from NOS testing

RemoteControl/CMakeLists.txt, RemoteControl/RemoteControl.config
A few RemoteControl plugin changes drafted after NOS testing with the latest framework.
Commit 1 (64aeb5a94d6a) is for making the key release timeout configurable via cmake.
Commit 2 (55dce874ab12) is for fixing a new deadlock use case when plugin activation is done by autostarting it on boot.
All of the changes are required for correct operation of the RemoteControl plugin under the use cases required by NOS.
=> RemoteControl: Fixes from NOS testing

Compositor/Compositor.config, Compositor/lib/Wayland/CMakeLists.txt, Compositor/lib/Wayland/Westeros.cpp
- introduced new field in json config for cursor file
- enabling cursor only if any file mentioned in the json config
- reading PNG image in ARGB888 format as westeros expects
Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>
=> enable cursor on westeros compositor

RemoteControl/LinuxDevice.cpp
Modified Pair() and Unpair() methods for KeyDevice class to send pairing events.
However at present, Unpair() method of KeyDevice class is not being called from anywhere. Should it be called in the  KeyDevice destructor.
=> Fix for WPE-438 - Modified Linux Device to send pairing events

Power/CMakeLists.txt, Power/PowerImplementation/Broadcom/PowerImplementation.cpp
It was observed that the Power plugin was not getting build for the
nexus when even if nexus is available. The reason being that the check
to build with nexus was using wrong variable after the refactoring.
Also, the pmlibs where not even getting linked resulting in undefined
references.
=> power: fixes power plugin not getting build for nexus

Spark/SparkJsonRpc.cpp, WebKitBrowser/WebKitBrowserJsonRpc.cpp
This issue is causing hang on the WebKit plugin, once we call a state() through the json rpc (or just load the Controller UI for WebKitBrowser info/settigns)
=> WebKit, Spark: release StateControl after use

Compositor/lib/Nexus/Implementation.cpp, Compositor/lib/Nexus/NexusServer/Settings.h, Compositor/lib/Wayland/Wayland.cpp
Currenlty the Wayland Compositor build is failing due to the missing of Resolution part. So moved Resolution part to NexusServer Layer, since this is common for both Nexus and Wayland-Nexus case. 
Seems Resolution Apis also need to be updated for Nexus/Wayland-Nexus cases , since they are sharing same methods. But not touched that part, since this will be taken care as part of ticket [WPE-571](https://metrological.atlassian.net/browse/WPE-571?)
=> Compositor:Wayland/Nexus to support reslution param

DeviceIdentification/Implementation/Nexus/Nexus.cpp, DisplayInfo/Nexus/PlatformImplementation.cpp, RemoteControl/IRRemote.cpp, VolumeControl/Nexus/VolumeControlPlatform.cpp
By default, Nexus expects will wait for all joined clients to
acknowledge standby notifications when using Nexus for going to standby.
It waits for those acknowledgments for some time (usually 10 secs)
before going to standby, which causes a large delay to complete standby
in case the clients don't acknowledge.
All plugins currently joining Nexus are, by default, not acknowledging
the standby, so they should call NxClient_UnregisterAcknowledgeStandby()
after joining so that Nexus doesn't wait for them when going to standby.
Make the NxClient_UnregisterAcknowledgeStandby() after NxClient_Join()
for all plugins currently joining Nexus and not doing any standby
acknowledgement.
=> [Nexus] Unregister standby acknowledgements after joining

Streamer/Frontend.h, Streamer/StreamerJsonRpc.cpp
During the stop sequence Player is firing the StateChange event through the decoder Event interface. This interface use registered callback to send to the requesters. But this callback is releasing before detaching the player and not setting it to nullptr
=> Streamer: fix to avoid crash during the stop
